/*:
 * @target MZ
 * @plugindesc picturesフォルダ全画像をデプロイメント時に保持します
 * @author マミタロス
 *
 * @help
 * img/pictures 内の画像を「未使用ファイルを除外する」対象から保護するだけのプラグインです。
 * 実行時処理はありません。
 *
 * @requiredAssets img/pictures/background
 * @requiredAssets img/pictures/background_alley
 * @requiredAssets img/pictures/background_alley_night
 * @requiredAssets img/pictures/background_corridor
 * @requiredAssets img/pictures/background_mio_room_night
 * @requiredAssets img/pictures/background_riverside_night
 * @requiredAssets img/pictures/background_town
 * @requiredAssets img/pictures/background_town_night
 * @requiredAssets img/pictures/backgroundtest
 * @requiredAssets img/pictures/bg_episode_select_kin
 * @requiredAssets img/pictures/bg_episode_select_momo
 * @requiredAssets img/pictures/bg_episode_select_ryu
 * @requiredAssets img/pictures/bg_episode_select_ura
 * @requiredAssets img/pictures/bg_story_route_select
 * @requiredAssets img/pictures/blackfade
 * @requiredAssets img/pictures/btn_auto_off
 * @requiredAssets img/pictures/btn_auto_on
 * @requiredAssets img/pictures/btn_character_change
 * @requiredAssets img/pictures/btn_history
 * @requiredAssets img/pictures/btn_possess
 * @requiredAssets img/pictures/btn_story
 * @requiredAssets img/pictures/btn_story_exit
 * @requiredAssets img/pictures/btn_talk
 * @requiredAssets img/pictures/btn_ui_hide
 * @requiredAssets img/pictures/button_random_possession_off
 * @requiredAssets img/pictures/button_random_possession_on
 * @requiredAssets img/pictures/CG_kintaros_ep01_01
 * @requiredAssets img/pictures/CG_kintaros_ep01_02
 * @requiredAssets img/pictures/CG_kintaros_ep07_01
 * @requiredAssets img/pictures/CG_kintaros_ep10_01
 * @requiredAssets img/pictures/CG_kintaros_ep10_02
 * @requiredAssets img/pictures/CG_kintaros_ep10_03
 * @requiredAssets img/pictures/CG_kintaros_ep11_01
 * @requiredAssets img/pictures/CG_kintaros_ep11_02
 * @requiredAssets img/pictures/CG_kintaros_ep11_03
 * @requiredAssets img/pictures/CG_kintaros_ep11_04
 * @requiredAssets img/pictures/CG_momotaros_ep04_01
 * @requiredAssets img/pictures/CG_momotaros_ep04_02
 * @requiredAssets img/pictures/CG_momotaros_ep04_03
 * @requiredAssets img/pictures/CG_momotaros_ep05_01
 * @requiredAssets img/pictures/CG_momotaros_ep09_01
 * @requiredAssets img/pictures/CG_momotaros_ep09_02
 * @requiredAssets img/pictures/CG_momotaros_ep12_01
 * @requiredAssets img/pictures/CG_momotaros_ep12_2_01
 * @requiredAssets img/pictures/CG_momotaros_ep12_2_02
 * @requiredAssets img/pictures/CG_momotaros_ep12_2_03
 * @requiredAssets img/pictures/CG_momotaros_ep12_2_04
 * @requiredAssets img/pictures/CG_ryutaros_ep05_01
 * @requiredAssets img/pictures/CG_ryutaros_ep05_02
 * @requiredAssets img/pictures/CG_ryutaros_ep05_03
 * @requiredAssets img/pictures/CG_ryutaros_ep05_04
 * @requiredAssets img/pictures/CG_ryutaros_ep08_01
 * @requiredAssets img/pictures/CG_ryutaros_ep10_01
 * @requiredAssets img/pictures/CG_ryutaros_ep12_01
 * @requiredAssets img/pictures/CG_ryutaros_ep12_02
 * @requiredAssets img/pictures/CG_ryutaros_ep12_03
 * @requiredAssets img/pictures/CG_urataros_ep02_01
 * @requiredAssets img/pictures/CG_urataros_ep04_01
 * @requiredAssets img/pictures/CG_urataros_ep04_02
 * @requiredAssets img/pictures/CG_urataros_ep04_03
 * @requiredAssets img/pictures/CG_urataros_ep08_01
 * @requiredAssets img/pictures/CG_urataros_ep08_02
 * @requiredAssets img/pictures/CG_urataros_ep08_03
 * @requiredAssets img/pictures/CG_urataros_ep11_01
 * @requiredAssets img/pictures/CGtest
 * @requiredAssets img/pictures/menu_console_panel
 * @requiredAssets img/pictures/menu_item_change
 * @requiredAssets img/pictures/menu_item_change_hover
 * @requiredAssets img/pictures/menu_item_possess
 * @requiredAssets img/pictures/menu_item_possess_hover
 * @requiredAssets img/pictures/message_DenO
 * @requiredAssets img/pictures/message_window
 * @requiredAssets img/pictures/message_window_frame
 * @requiredAssets img/pictures/message_window_inner
 * @requiredAssets img/pictures/name_hana
 * @requiredAssets img/pictures/name_kintaros
 * @requiredAssets img/pictures/name_mio
 * @requiredAssets img/pictures/name_momotaros
 * @requiredAssets img/pictures/name_naomi
 * @requiredAssets img/pictures/name_ryotaro
 * @requiredAssets img/pictures/name_ryutaros
 * @requiredAssets img/pictures/name_urataros
 * @requiredAssets img/pictures/portrait_hana_base_default_angry
 * @requiredAssets img/pictures/portrait_hana_base_default_normal
 * @requiredAssets img/pictures/portrait_hana_base_default_smile
 * @requiredAssets img/pictures/portrait_kintaros_base_default_angry
 * @requiredAssets img/pictures/portrait_kintaros_base_default_cry
 * @requiredAssets img/pictures/portrait_kintaros_base_default_normal
 * @requiredAssets img/pictures/portrait_kintaros_base_default_sleep
 * @requiredAssets img/pictures/portrait_kintaros_base_default_smile
 * @requiredAssets img/pictures/portrait_momotaros_base_default_angry
 * @requiredAssets img/pictures/portrait_momotaros_base_default_angryshy
 * @requiredAssets img/pictures/portrait_momotaros_base_default_apology
 * @requiredAssets img/pictures/portrait_momotaros_base_default_awkward
 * @requiredAssets img/pictures/portrait_momotaros_base_default_grin
 * @requiredAssets img/pictures/portrait_momotaros_base_default_normal
 * @requiredAssets img/pictures/portrait_momotaros_base_default_restrainedshy
 * @requiredAssets img/pictures/portrait_momotaros_base_default_shy
 * @requiredAssets img/pictures/portrait_momotaros_base_default_soft
 * @requiredAssets img/pictures/portrait_momotaros_base_default_surprised
 * @requiredAssets img/pictures/portrait_naomi_base_default_normal
 * @requiredAssets img/pictures/portrait_naomi_base_default_smile
 * @requiredAssets img/pictures/portrait_ryotaro_base_ryotaro_normal
 * @requiredAssets img/pictures/portrait_ryotaro_base_ryotaro_shy
 * @requiredAssets img/pictures/portrait_ryotaro_base_ryotaro_smile
 * @requiredAssets img/pictures/portrait_ryotaro_base_ryotaro_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_base_ryotaro_worried
 * @requiredAssets img/pictures/portrait_ryotaro_base_urataros_tired
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_sleep
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_kintaros_smileshy
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_momotaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_momotaros_crypng
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_momotaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_momotaros_sleep
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_momotaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryotaro_angry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryotaro_cry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryotaro_normal
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryotaro_sleep
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryotaro_smile
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryutaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryutaros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryutaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryutaros_sleep
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_ryutaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_urataros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_urataros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_urataros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_urataros_sleep
 * @requiredAssets img/pictures/portrait_ryotaro_kintaros_urataros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_angryshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_apology
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_awkward
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_grin
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_kintaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_angryshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_apology
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_awkward
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_grin
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_restrainedshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_selfconscious
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_soft
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_momotaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_angry
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_angryshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_apology
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_awkward
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_grin
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_normal
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_restrainedshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_shy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_soft
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryotaro_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_angryshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_apology
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_awkward
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_grin
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_ryutaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_angryshy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_apology
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_awkward
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_grin
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_momotaros_urataros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_kintaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_kintaros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_kintaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_kintaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_kintaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_kintaros_worried
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_momotaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_momotaros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_momotaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_momotaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_momotaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_momotaros_worried
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_angry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_cry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_jealous
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_normal
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_smile
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryotaro_worried
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_jealous
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_ryutaros_worried
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_urataros_angry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_urataros_cry
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_urataros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_urataros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_urataros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_ryutaros_urataros_worried
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_kintaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_kintaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_kintaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_kintaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_kintaros_wrysmile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_momotaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_momotaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_momotaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_momotaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_momotaros_wrysmile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryotaro_normal
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryotaro_shy
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryotaro_smile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryotaro_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryotaro_wrysmile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryutaros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryutaros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryutaros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryutaros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_ryutaros_wrysmile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_normal
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_serious
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_shy
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_smile
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_surprised
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_unguardedshy
 * @requiredAssets img/pictures/portrait_ryotaro_urataros_urataros_wrysmile
 * @requiredAssets img/pictures/portrait_ryutaros_base_default_angry
 * @requiredAssets img/pictures/portrait_ryutaros_base_default_cry
 * @requiredAssets img/pictures/portrait_ryutaros_base_default_normal
 * @requiredAssets img/pictures/portrait_ryutaros_base_default_smile
 * @requiredAssets img/pictures/portrait_ryutaros_base_default_surprised
 * @requiredAssets img/pictures/portrait_ryutaros_base_default_worried
 * @requiredAssets img/pictures/portrait_urataros_base_default_normal
 * @requiredAssets img/pictures/portrait_urataros_base_default_shy
 * @requiredAssets img/pictures/portrait_urataros_base_default_smile
 * @requiredAssets img/pictures/portrait_urataros_base_default_surprised
 * @requiredAssets img/pictures/portrait_urataros_base_default_wrysmile
 * @requiredAssets img/pictures/ui_episode_back
 * @requiredAssets img/pictures/ui_episode_kin_01
 * @requiredAssets img/pictures/ui_episode_kin_02
 * @requiredAssets img/pictures/ui_episode_kin_03
 * @requiredAssets img/pictures/ui_episode_kin_04
 * @requiredAssets img/pictures/ui_episode_kin_05
 * @requiredAssets img/pictures/ui_episode_kin_06
 * @requiredAssets img/pictures/ui_episode_kin_07
 * @requiredAssets img/pictures/ui_episode_kin_08
 * @requiredAssets img/pictures/ui_episode_kin_09
 * @requiredAssets img/pictures/ui_episode_kin_10
 * @requiredAssets img/pictures/ui_episode_kin_11
 * @requiredAssets img/pictures/ui_episode_kin_12
 * @requiredAssets img/pictures/ui_episode_momo_01
 * @requiredAssets img/pictures/ui_episode_momo_02
 * @requiredAssets img/pictures/ui_episode_momo_03
 * @requiredAssets img/pictures/ui_episode_momo_04
 * @requiredAssets img/pictures/ui_episode_momo_05
 * @requiredAssets img/pictures/ui_episode_momo_06
 * @requiredAssets img/pictures/ui_episode_momo_07
 * @requiredAssets img/pictures/ui_episode_momo_08
 * @requiredAssets img/pictures/ui_episode_momo_09
 * @requiredAssets img/pictures/ui_episode_momo_10
 * @requiredAssets img/pictures/ui_episode_momo_11
 * @requiredAssets img/pictures/ui_episode_momo_12
 * @requiredAssets img/pictures/ui_episode_ryu_01
 * @requiredAssets img/pictures/ui_episode_ryu_02
 * @requiredAssets img/pictures/ui_episode_ryu_03
 * @requiredAssets img/pictures/ui_episode_ryu_04
 * @requiredAssets img/pictures/ui_episode_ryu_05
 * @requiredAssets img/pictures/ui_episode_ryu_06
 * @requiredAssets img/pictures/ui_episode_ryu_07
 * @requiredAssets img/pictures/ui_episode_ryu_08
 * @requiredAssets img/pictures/ui_episode_ryu_09
 * @requiredAssets img/pictures/ui_episode_ryu_10
 * @requiredAssets img/pictures/ui_episode_ryu_11
 * @requiredAssets img/pictures/ui_episode_ryu_12
 * @requiredAssets img/pictures/ui_episode_selected_kin
 * @requiredAssets img/pictures/ui_episode_selected_momo
 * @requiredAssets img/pictures/ui_episode_selected_ryu
 * @requiredAssets img/pictures/ui_episode_selected_ura
 * @requiredAssets img/pictures/ui_episode_start_kin
 * @requiredAssets img/pictures/ui_episode_start_momo
 * @requiredAssets img/pictures/ui_episode_start_ryu
 * @requiredAssets img/pictures/ui_episode_start_ura
 * @requiredAssets img/pictures/ui_episode_ura_01
 * @requiredAssets img/pictures/ui_episode_ura_02
 * @requiredAssets img/pictures/ui_episode_ura_03
 * @requiredAssets img/pictures/ui_episode_ura_04
 * @requiredAssets img/pictures/ui_episode_ura_05
 * @requiredAssets img/pictures/ui_episode_ura_06
 * @requiredAssets img/pictures/ui_episode_ura_07
 * @requiredAssets img/pictures/ui_episode_ura_08
 * @requiredAssets img/pictures/ui_episode_ura_09
 * @requiredAssets img/pictures/ui_episode_ura_10
 * @requiredAssets img/pictures/ui_episode_ura_11
 * @requiredAssets img/pictures/ui_episode_ura_12
 * @requiredAssets img/pictures/ui_story_pass_kin
 * @requiredAssets img/pictures/ui_story_pass_momo
 * @requiredAssets img/pictures/ui_story_pass_ryuta
 * @requiredAssets img/pictures/ui_story_pass_ura
 * @requiredAssets img/pictures/window_history_entry
 * @requiredAssets img/pictures/window_history_frame
 */

(() => {
    "use strict";
})();
