// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Mami_ChoiceCursorAnime","status":true,"description":"選択肢とタイトル画面にアニメーションカーソルを表示します。","parameters":{"ImageName":"ChoiceCursor","FrameWidth":"84","FrameHeight":"50","Frames":"8","Speed":"5","Scale":"1.00","HideDefaultCursor":"true","ChoiceOffsetX":"-35","ChoiceOffsetY":"10","TitleOffsetX":"-35","TitleOffsetY":"10"}}
];
