// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Mami_SkipTitle","status":true,"description":"タイトル画面を飛ばして、起動後すぐにニューゲームを開始します。","parameters":{}},
{"name":"Mami_TimeSystem","status":true,"description":"時間帯管理システム Ver1.0","parameters":{}},
{"name":"Mami_DenOMessageUI","status":true,"description":"電王会話作品用・画像式メッセージUI Ver1.0","parameters":{"WindowX":"100","WindowY":"500","WindowWidth":"1120","WindowHeight":"200","Padding":"24","TextStartX":"20","TextStartY":"-3","FontSize":"28","LineHeight":"0","TextColor":"#ffffff","OutlineColor":"rgba(0,0,0,0.75)","OutlineWidth":"4","FrameImage":"message_window","FrameOffsetX":"-20","FrameOffsetY":"-15","FrameScaleX":"100","FrameScaleY":"100","FrameOpacity":"255","NamePlateX":"200","NamePlateY":"470","NamePlateScale":"100","NamePlateOpacity":"255","FollowWindowOpenness":"true","HideDuringFastForward":"false"}},
{"name":"Mami_NovelUI_EndOfText","status":true,"description":"各メッセージページの文末に送り用アニメーションを表示します Ver1.0","parameters":{"Image":"message_DenO","FrameWidth":"57","FrameHeight":"57","FrameCount":"4","AnimationSpeed":"10","Horizontal":"true","OffsetX":"0","OffsetY":"0","Scale":"50","Opacity":"255","Loop":"true","Debug":"false"}},
{"name":"Mami_DenOUI","status":true,"description":"電王会話作品専用UI Ver2.0","parameters":{"DisabledOpacity":"120","HoverScale":"1.05","PressedScale":"0.97","AnimationSpeed":"0.20"}},
{"name":"Mami_DenOTalk","status":true,"description":"電王会話作品用・複数話者対応ランダム会話 Ver0.1","parameters":{"PictureId":"2","PictureX":"640","PictureY":"360","Scale":"100","DefaultExpression":"portrait_ryotaro_base_ryotaro_normal","DefaultSpeaker":"ryotaro","ResetDelay":"15","HistoryCount":"20"}},
{"name":"Mami_DenOIdleTalk","status":true,"description":"電王会話作品用・放置台詞 Ver1.0","parameters":{"FirstIdleSeconds":"30","NextIdleMinSeconds":"45","NextIdleMaxSeconds":"75","PictureId":"2","PictureX":"640","PictureY":"360","Scale":"100","DefaultExpression":"portrait_ryotaro_base_ryotaro_normal","ResetDelay":"15"}},
{"name":"Mami_DisableMenu","status":true,"description":"標準メニューとキャンセル操作を無効化します。","parameters":{}}
];
